### PR TITLE
Add comments to config files

### PR DESCRIPTION
**Pull request by willingc**
This PR adds some comments to the config files and creates a directory with config files that have guidance to the user on editing. Ultimately we should probably prompt the user for key info and then use in the files.

### CODE REVIEW

**Comment by willingc** [comment]
Not quite sure why some of the PyData 2016 London videos including this one were removed.

**Comment by minrk** [comment]
I'm not sure why the video is gone. I'll have to ask them.

**Comment by minrk** [comment]
Apparently there were sync issues with some PyData videos. They are being reprocessed and should be reposted shortly.

**Comment by willingc** [comment]
Thanks for checking @minrk. I spoke at the Minneapolis Python user group meeting last night about user groups and JupyterHub with a call to action for them to use the hub for a future workshop or meeting. There are 60 people looking forward to viewing your talk and the concept of reference deployments was very well received. On another note, the first speaker gave his talk using RISE and had very positive things to say about it @damianavila :smile:
cc/ @jamieshq

**Comment by damianavila** [comment]
Thanks for the report @willingc... It is always nice to see people using it... still, I have to put some more love on RISE :wink:

**Comment by willingc** [comment]
@damianavila The presenter really liked it for his math analysis/visualization and especially for the ability to execute code during the talk. I asked him how he heard about it; he googled "Jupyter live presentation".  [Slide reference to RISE.](http://www.evanoman.com/Presentations/PyMNtosPresentation.html#/13) [Evan Oman's very interesting notebook for talk on GitHub](https://github.com/EvanOman/PyMNtos-Pres/blob/master/python/Presentation%20Notebook.ipynb) cc/ @evanoman Thanks for the presentation last night.

**Pull request merged**
